name: traffic_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.16
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  photo_view: ^0.14.0
  flutter_rating_bar: ^4.0.1
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  gallery_saver: ^2.3.2
  flutter_native_image: ^0.0.6+1
  exif: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image.jpg
    - assets/images/no_internet.png